services:
  app:
    image: gabzsz/auth_converter:latest
    ports:
      - "8523:80"
    env_file:
      - stack.env
    depends_on:
      - database
      - redis
    restart: unless-stopped

  database:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.track=all"
      - "-c"
      - "pg_stat_statements.track_utility=on"
      - "-c"
      - "pg_stat_statements.max=10000"
    env_file:
      - stack.env
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    env_file:
      - stack.env
    # healthcheck:
    #   test: ["CMD", "redis-cli", "ping"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
